name: 'Run a Dockerized R app'
description: |
  Run a Dockerized R app on GitHub Actions, and deploy the results
  to GitHub Pages.
inputs:
  branch:
    description: |
      Branch to publish, default is `gh-pages`.
    default: gh-pages
runs:
  using: composite
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.branch }}
  - name: Run
    run: |
      docker pull ghcr.io/${{ github.repository }}:latest
      docker run -e CI=true -e GITHUB_ACTIONS=true \
        -e GITHUB_WORKSPACE=/__w -e RUNNER_TEMP=/tmp \
        -v ${GITHUB_WORKSPACE}:/__w \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -w /app Rscript index.R
    shell: bash
  - name: Deploy to GitHub pages 🚀
    uses: JamesIves/github-pages-deploy-action@v4.6.8
    with:
      clean: false
      branch: ${{ inputs.branch }}
      folder: .
